
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    # Applies to all files under models/example/
    example:
      materialized: view
    src:
      src_test:
        +materialized: view
        +schema: RBOK_GA
      src_base_test:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_SNAPSHOT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_SNAPSHOT_v2:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_SNAPSHOT_v3:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_SNAPSHOT_v4:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_SNAPSHOT_v5:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_SNAPSHOT_v6:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_SNAPSHOT_RPT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      LAST_TOUCH_TRAFFIC:
        +materialized: view
        +schema: ECOM_ANALYTICS
      LAST_TOUCH_EP:
        +materialized: view
        +schema: ECOM_ANALYTICS
      FACT_RETAIL_SALES_RPT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      FACT_INVENTORY_RPT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      FACT_DEMAND_RPT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      FACT_STORE_HOUR_COUNTS_RPT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      DIM_LOCATION_RPT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      DIM_PRODUCT_RPT:
        +materialized: view
        +schema: ECOM_ANALYTICS
      RETAIL_SALES_AGGREGATED:
        +materialized: view
        +schema: ECOM_ANALYTICS
      GA4_AGGREGATED:
        +materialized: view
        +schema: ECOM_ANALYTICS
      INVENTORY_AGGREGATED:
        +materialized: view
        +schema: ECOM_ANALYTICS
      REEBOK_FACT_AGGREGATED_COMBINED:
        +materialized: view
        +schema: ECOM_ANALYTICS
      