{{ config(materialized="table", database="RBOK_RPT", schema="ECOM_ANALYTICS") }}

Select
LOCATION_PK,
SPARC_LOCATION_ID,
BRAND_LOCATION_ID,
LOCATION_NAME,
SUB_CHANNEL_ID,
SUB_CHANNEL,
CHANNEL_ID,
CHANNEL,
OPEN_DATE,
CLOSE_DATE,
CITY,
STATE,
POSTAL_CODE,
COUNTRY,
LATITUDE,
LONGITUDE
FROM SPARC_BASE.ECOM_ANALYTICS.DIM_LOCATION