{{ config(materialized="table", database="RBOK_RPT", schema="ECOM_ANALYTICS") }}

Select
LOCATION_PK,
BRAND_LOCATION,
INVENTORY_DATE,
ITEM_PK,
MARKDOWN_STATUS,
MARKUP_STATUS,
ON_HAND_UNITS,
IN_TRANSIT_UNITS,
ON_ORDER_UNITS,
TOTAL_ON_HAND_UNITS,
TOTAL_MARKDOWN_UNITS,
ON_HAND_DOLLARS_USD,
IN_TRANSIT_DOLLARS_USD,
ON_ORDER_DOLLARS_USD,
TOTAL_ON_HAND_DOLLARS_USD,
STORE_MARKDOWN_DOLLARS_USD,
IN_TRANSIT_MARKDOWN_DOLLARS_USD,
ON_ORDER_MARKDOWN_DOLLARS_USD,
TOTAL_MARKDOWN_DOLLARS_USD,
QUANTITY_RECEIVED,
QUANTITY_SOLD
FROM SPARC_BASE.ECOM_ANALYTICS.FACT_INVENTORY