{{ config(materialized="table", database="RBOK_RPT", schema="ECOM_ANALYTICS") }}

Select 
LOCATION_PK,
BRAND_LOCATION,
TRANSACTION_DATE,
TRANSACTION_ID,
ITEM_PK,
UNITS_SOLD,
GROSS_SALES_USD,
DISCOUNT_REASON_CODE,
COST_UNIT_USD,
COST_USD,
BASE_RETAIL_VALUE_USD,
TAX_USD,
PROMOTION_ID,
TRANSACTION_TYPE_CODE,
TRANSACTION_CURRENCY,
PROMO_MARKDOWN_USD,
TOTAL_MARKDOWNS_USD,
SELLING_CHANNEL_ID,
ORDER_TYPE_ID
FROM SPARC_BASE.ECOM_ANALYTICS.FACT_RETAIL_SALES