{{ config(materialized="table", database="SPARC_BASE", schema="ECOM_ANALYTICS") }}

Select distinct GA4.*,
Traffic.TRAFFIC_SOURCE_NAME as LastTouch_Traffic_Name,
Traffic.TRAFFIC_SOURCE_MEDIUM as LastTouch_Traffic_Medium,
Traffic.TRAFFIC_SOURCE_SOURCE as LastTouch_Traffic_Source,
Product.DIVISION_NAME,
Product.KEY_CATEGORY_DESC,
Product.BUSINESS_SEGMENT_DESC
from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4" as GA4
LEFT JOIN "SPARC_BASE"."ECOM_ANALYTICS"."LAST_TOUCH_TRAFFIC" as Traffic ON Traffic.USER_SESSION_KEY=GA4.USER_SESSION_KEY
LEFT JOIN 
(
Select distinct 
Product.Article,
Product.DIVISION_NAME,
Product.KEY_CATEGORY_DESC,
Product.BUSINESS_SEGMENT_DESC
from "SPARC_BASE"."ECOM_ANALYTICS"."DIM_PRODUCT" as Product
WHERE KEY_CATEGORY_DESC is not null AND BUSINESS_SEGMENT_DESC is not null AND KEY_CATEGORY_DESC!='' AND BUSINESS_SEGMENT_DESC!=''
)
as Product ON Product.ARTICLE=GA4.ITEMS_ITEM_ID
ORDER BY USER_SESSION_KEY, EVENT_TIMESTAMP DESC