{{ config(materialized="table", database="RBOK_RPT", schema="ECOM_ANALYTICS") }}

WITH 
CLEAN_GA4_EVENT_PARAMS_VALUE AS
(
	SELECT
                TO_DATE(EVENT_DATE,'YYYYMMDD') as EVENT_DATE,
                TO_TIMESTAMP(SUBSTR(EVENT_TIMESTAMP,1,13)) as EVENT_TIMESTAMP,
                EVENT_NAME,
                EVENT_PARAMS_KEY,
                 (CASE
                     WHEN EVENT_PARAMS_VALUE_STRING_VALUE IS NOT NULL THEN TO_VARIANT(EVENT_PARAMS_VALUE_STRING_VALUE)
                     WHEN EVENT_PARAMS_VALUE_INT_VALUE IS NOT NULL THEN TO_VARIANT(EVENT_PARAMS_VALUE_INT_VALUE)
                     WHEN EVENT_PARAMS_VALUE_FLOAT_VALUE IS NOT NULL THEN TO_VARIANT(EVENT_PARAMS_VALUE_FLOAT_VALUE)
                     WHEN EVENT_PARAMS_VALUE_DOUBLE_VALUE IS NOT NULL THEN TO_VARIANT(EVENT_PARAMS_VALUE_DOUBLE_VALUE)
                  ELSE NULL
                 END) AS EVENT_PARAMS_VALUE,
                 EVENT_BUNDLE_SEQUENCE_ID,
                 USER_PSEUDO_ID,
                 ecommerce_transaction_id,
                 device_category ,
	    		 TRAFFIC_SOURCE_NAME ,
	    		 TRAFFIC_SOURCE_MEDIUM ,
	    		 TRAFFIC_SOURCE_SOURCE ,
                 items_item_id , 
                 items_item_brand ,  
                 items_item_category2 ,
                 ITEMS_PRICE_IN_USD ,
                 ITEMS_QUANTITY ,
                 ITEMS_ITEM_REVENUE_IN_USD
          FROM SPARC_RAW.RBOK_GA.GA4_EVENTS_RAW
),
FIRST_GA4_FLATTEN AS
(
	SELECT
        EVENT_DATE ,
        EVENT_TIMESTAMP,
    	EVENT_NAME as EVENT_NAME_ORIGINAL,
        EVENT_NAME ,
    	1 as EVENT_NAME_FLAG,
        EVENT_BUNDLE_SEQUENCE_ID,
        USER_PSEUDO_ID ,
        ECOMMERCE_TRANSACTION_ID, 
        DEVICE_CATEGORY ,
	    TRAFFIC_SOURCE_NAME ,
	    TRAFFIC_SOURCE_MEDIUM ,
	    TRAFFIC_SOURCE_SOURCE ,
        ITEMS_ITEM_ID ,
        ITEMS_ITEM_BRAND ,
        ITEMS_ITEM_CATEGORY2 ,
        ITEMS_PRICE_IN_USD ,
        ITEMS_QUANTITY ,
        ITEMS_ITEM_REVENUE_IN_USD,
        TO_VARCHAR("'page_type'") as EP_PAGE_TYPE,
        TO_VARCHAR("'page_owner'") as EP_PAGE_OWNER,
        TO_NUMBER("'entrances'") as EP_ENTRANCES,
        TO_VARCHAR("'ga_session_id'") as EP_GA_SESSION_ID,
        CONCAT(USER_PSEUDO_ID,'|',EP_GA_SESSION_ID) as USER_SESSION_KEY,
        TO_NUMBER("'checkout_orderdiscountvalue'",10,2) as EP_CHECKOUT_ORDERDISCOUNTVALUE
        FROM CLEAN_GA4_EVENT_PARAMS_VALUE AS data_to_pivot
        PIVOT (
          MAX(EVENT_PARAMS_VALUE) FOR EVENT_PARAMS_KEY IN ('page_type','page_owner','entrances','ga_session_id','checkout_orderdiscountvalue')
        ) AS pivoted_data
),
SECOND_GA4_FLATTEN AS
(
Select
(CASE
    WHEN EVENT_NAME_ORIGINAL='add_to_cart' THEN 1
    WHEN EVENT_NAME_ORIGINAL='view_cart' THEN 2
    WHEN EVENT_NAME_ORIGINAL='begin_checkout' THEN 3
    WHEN EVENT_NAME_ORIGINAL='add_shipping_info' THEN 4
    WHEN EVENT_NAME_ORIGINAL='add_payment_info' THEN 5
    WHEN EVENT_NAME_ORIGINAL='review_order' THEN 6
    WHEN EVENT_NAME_ORIGINAL='purchase' THEN 7
    ELSE NULL
END) as CHECKOUT_STAGE_ORDER,
MAX(CHECKOUT_STAGE_ORDER) OVER (PARTITION BY USER_SESSION_KEY) AS MAX_CHECKOUT_STAGE_ORDER,
(CASE 
    WHEN MAX_CHECKOUT_STAGE_ORDER=1 THEN 'add_to_cart'
    WHEN MAX_CHECKOUT_STAGE_ORDER=2 THEN 'view_cart' 
    WHEN MAX_CHECKOUT_STAGE_ORDER=3 THEN 'begin_checkout' 
    WHEN MAX_CHECKOUT_STAGE_ORDER=4 THEN 'add_shipping_info'
    WHEN MAX_CHECKOUT_STAGE_ORDER=5 THEN 'add_payment_info' 
    WHEN MAX_CHECKOUT_STAGE_ORDER=6 THEN 'review_order' 
    WHEN MAX_CHECKOUT_STAGE_ORDER=7 THEN 'purchase'
    ELSE NULL
END) AS MAX_CHECKOUT_STAGE,
EVENT_DATE,
EVENT_TIMESTAMP ,
EVENT_NAME_ORIGINAL,
USER_SESSION_KEY,
EVENT_BUNDLE_SEQUENCE_ID,
USER_PSEUDO_ID,
ECOMMERCE_TRANSACTION_ID,
DEVICE_CATEGORY,
TRAFFIC_SOURCE_NAME ,
TRAFFIC_SOURCE_MEDIUM ,
TRAFFIC_SOURCE_SOURCE ,
(CASE WHEN EVENT_NAME_ORIGINAL='purchase' THEN ITEMS_QUANTITY ELSE NULL END) AS UNITS_ORDERED,
ITEMS_ITEM_ID,
ITEMS_ITEM_BRAND as FRANCHISE,
ITEMS_ITEM_CATEGORY2 as GENDER,
ITEMS_PRICE_IN_USD ,
ITEMS_ITEM_REVENUE_IN_USD,
EP_PAGE_TYPE,
EP_PAGE_OWNER,
EP_ENTRANCES,
EP_GA_SESSION_ID,
EP_CHECKOUT_ORDERDISCOUNTVALUE,
TO_NUMBER("'add_to_cart'") as EVENT_ADD_TO_CART,
TO_NUMBER("'login'") as EVENT_LOGIN,
TO_NUMBER("'view_item'") as EVENT_VIEW_ITEM,
TO_NUMBER("'begin_checkout'") as EVENT_BEGIN_CHECKOUT,
TO_NUMBER("'select_item'") as EVENT_SELECT_ITEM,
TO_NUMBER("'first_visit'") as EVENT_FIRST_VISIT,
TO_NUMBER("'session_start'") as EVENT_SESSION_START,
TO_NUMBER("'purchase'") as EVENT_PURCHASE,
TO_NUMBER("'search'") as EVENT_SEARCH,
TO_NUMBER("'remove_from_cart'") as EVENT_REMOVE_FROM_CART,
TO_NUMBER("'user_engagement'") as EVENT_USER_ENGAGEMENT,
TO_NUMBER("'view_item_list'") as EVENT_VIEW_ITEM_LIST,
TO_NUMBER("'page_view'") as EVENT_PAGE_VIEW,
TO_NUMBER("'add_payment_info'") as EVENT_ADD_PAYMENT_INFO,
TO_NUMBER("'add_to_wishlist'") as EVENT_ADD_TO_WISHLIST,
TO_NUMBER("'sign_up_newsletter'") as EVENT_SIGN_UP_NEWSLETTER,
TO_NUMBER("'sign_up'") as EVENT_SIGN_UP,
TO_NUMBER("'view_cart'") as EVENT_VIEW_CART,
TO_NUMBER("'add_shipping_info'") as EVENT_ADD_SHIPPING_INFO,
TO_NUMBER("'navigation'") as EVENT_NAVIGATION,
TO_NUMBER("'select_promotion'") as EVENT_SELECT_PROMOTION,
TO_NUMBER("'view_search_results'") as EVENT_VIEW_SEARCH_RESULTS,
TO_NUMBER("'fetch_user_data'") as EVENT_FETCH_USER_DATA,
TO_NUMBER("'review_order'") as EVENT_REVIEW_ORDER,
TO_NUMBER("'error_404'") as EVENT_ERROR_404,
TO_NUMBER("'sort_applied'") as EVENT_SORT_APPLIED,
TO_NUMBER("'out_of_stock_signup'") as EVENT_OUT_OF_STOCK_SIGNUP,
TO_NUMBER("'filter_added'") as EVENT_FILTER_ADDED,
TO_NUMBER("'no_search_results'") as EVENT_NO_SEARCH_RESULTS,
TO_NUMBER("'form_error'") as EVENT_FORM_ERROR
from FIRST_GA4_FLATTEN AS data_to_pivot_1
PIVOT( MAX(EVENT_NAME_FLAG) FOR EVENT_NAME IN ('view_item','navigation','session_start','purchase','select_promotion','add_to_cart','login','begin_checkout','user_engagement','sign_up','view_search_results','remove_from_cart','fetch_user_data','review_order','error_404','sort_applied','first_visit','select_item','view_item_list','page_view','add_payment_info','add_to_wishlist','sign_up_newsletter','out_of_stock_signup','search','filter_added','no_search_results','add_shipping_info','view_cart','form_error')
) AS pivoted_data
),
LAST_TOUCH_TRAFFIC AS
(
Select * from(
(Select USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE
from (
Select distinct row_number() OVER(PARTITION BY USER_SESSION_KEY ORDER BY EVENT_TIMESTAMP DESC) AS Rank,
USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE
from SECOND_GA4_FLATTEN
WHERE USER_SESSION_KEY IN 
(
    Select distinct USER_SESSION_KEY from SECOND_GA4_FLATTEN
    WHERE EVENT_NAME_ORIGINAL='purchase'
    AND TRAFFIC_SOURCE_NAME is not null
    AND TRAFFIC_SOURCE_MEDIUM is not null 
    AND TRAFFIC_SOURCE_SOURCE is not null
)
AND EVENT_NAME_ORIGINAL='purchase'
AND TRAFFIC_SOURCE_NAME is not null AND TRAFFIC_SOURCE_MEDIUM is not null AND TRAFFIC_SOURCE_SOURCE is not null
GROUP BY USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL,TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE
ORDER BY USER_SESSION_KEY, EVENT_TIMESTAMP DESC
)
WHERE RANK=1)

UNION

(Select USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL,TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE
from (
Select distinct row_number() OVER(PARTITION BY USER_SESSION_KEY ORDER BY EVENT_TIMESTAMP DESC) AS Rank,USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL,TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE --EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from SECOND_GA4_FLATTEN
WHERE USER_SESSION_KEY NOT IN
(
    Select distinct USER_SESSION_KEY from SECOND_GA4_FLATTEN
    WHERE EVENT_NAME_ORIGINAL='purchase'
    AND TRAFFIC_SOURCE_NAME is not null
    AND TRAFFIC_SOURCE_MEDIUM is not null 
    AND TRAFFIC_SOURCE_SOURCE is not null
)
AND USER_SESSION_KEY IN
(
    Select distinct USER_SESSION_KEY from SECOND_GA4_FLATTEN
    WHERE (TRAFFIC_SOURCE_NAME is not null
    OR TRAFFIC_SOURCE_MEDIUM is not null
    OR TRAFFIC_SOURCE_SOURCE is not null)
)
AND (TRAFFIC_SOURCE_NAME is not null
    OR TRAFFIC_SOURCE_MEDIUM is not null
    OR TRAFFIC_SOURCE_SOURCE is not null)
GROUP BY USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL,TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE 
ORDER BY USER_SESSION_KEY, EVENT_TIMESTAMP DESC
)
WHERE RANK=1)

UNION

(Select USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL,TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE 
from (
Select distinct row_number() OVER(PARTITION BY USER_SESSION_KEY ORDER BY EVENT_TIMESTAMP DESC) AS Rank,USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE --EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from SECOND_GA4_FLATTEN
WHERE USER_SESSION_KEY NOT IN
(
    Select distinct USER_SESSION_KEY from SECOND_GA4_FLATTEN
    WHERE EVENT_NAME_ORIGINAL='purchase'
    AND TRAFFIC_SOURCE_NAME is not null
    AND TRAFFIC_SOURCE_MEDIUM is not null 
    AND TRAFFIC_SOURCE_SOURCE is not null
)
AND USER_SESSION_KEY NOT IN
(
    Select distinct USER_SESSION_KEY from SECOND_GA4_FLATTEN
    WHERE (TRAFFIC_SOURCE_NAME is not null
    OR TRAFFIC_SOURCE_MEDIUM is not null
    OR TRAFFIC_SOURCE_SOURCE is not null)
)
GROUP BY USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL,TRAFFIC_SOURCE_NAME, TRAFFIC_SOURCE_MEDIUM, TRAFFIC_SOURCE_SOURCE 
ORDER BY USER_SESSION_KEY, EVENT_TIMESTAMP DESC
)
WHERE RANK=1)
)
),
GA4_FINAL AS
(
SELECT
GA4.MAX_CHECKOUT_STAGE_ORDER,
GA4.MAX_CHECKOUT_STAGE,
GA4.CHECKOUT_STAGE_ORDER,
GA4.EVENT_DATE,
GA4.EVENT_TIMESTAMP,
GA4.EVENT_NAME_ORIGINAL,
GA4.USER_SESSION_KEY,
GA4.EVENT_BUNDLE_SEQUENCE_ID,
GA4.USER_PSEUDO_ID,
GA4.ECOMMERCE_TRANSACTION_ID,
GA4.DEVICE_CATEGORY,
GA4.UNITS_ORDERED,
GA4.ITEMS_ITEM_ID,
GA4.FRANCHISE,
GA4.GENDER,
GA4.ITEMS_PRICE_IN_USD,
GA4.ITEMS_ITEM_REVENUE_IN_USD,
GA4.EP_PAGE_TYPE,
GA4.EP_PAGE_OWNER,
GA4.EP_ENTRANCES,
GA4.EP_GA_SESSION_ID,
GA4.EP_CHECKOUT_ORDERDISCOUNTVALUE,
GA4.EVENT_ADD_TO_CART,
GA4.EVENT_LOGIN,
GA4.EVENT_VIEW_ITEM,
GA4.EVENT_BEGIN_CHECKOUT,
GA4.EVENT_SELECT_ITEM,
GA4.EVENT_FIRST_VISIT,
GA4.EVENT_SESSION_START,
GA4.EVENT_PURCHASE,
GA4.EVENT_SEARCH,
GA4.EVENT_REMOVE_FROM_CART,
GA4.EVENT_USER_ENGAGEMENT,
GA4.EVENT_VIEW_ITEM_LIST,
GA4.EVENT_PAGE_VIEW,
GA4.EVENT_ADD_PAYMENT_INFO,
GA4.EVENT_ADD_TO_WISHLIST,
GA4.EVENT_SIGN_UP_NEWSLETTER,
GA4.EVENT_SIGN_UP,
GA4.EVENT_VIEW_CART,
GA4.EVENT_ADD_SHIPPING_INFO,
GA4.EVENT_NAVIGATION,
GA4.EVENT_SELECT_PROMOTION,
GA4.EVENT_VIEW_SEARCH_RESULTS,
GA4.EVENT_FETCH_USER_DATA,
GA4.EVENT_REVIEW_ORDER,
GA4.EVENT_ERROR_404,
GA4.EVENT_SORT_APPLIED,
GA4.EVENT_OUT_OF_STOCK_SIGNUP,
GA4.EVENT_FILTER_ADDED,
GA4.EVENT_NO_SEARCH_RESULTS,
GA4.EVENT_FORM_ERROR,
Traffic.TRAFFIC_SOURCE_NAME AS LASTTOUCH_TRAFFIC_CAMPAIGN,
Traffic.TRAFFIC_SOURCE_MEDIUM AS LASTTOUCH_TRAFFIC_MEDIUM,
Traffic.TRAFFIC_SOURCE_SOURCE AS LASTTOUCH_TRAFFIC_SOURCE,
(CASE
    WHEN LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%affiliate%' THEN 'Affiliates'
    WHEN (LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%display%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%banner%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%expandable%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%interstitial%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%cpm%') THEN 'Display'
    WHEN LOWER(LASTTOUCH_TRAFFIC_MEDIUM)='organic' THEN 'Organic Search'
    WHEN (REGEXP_LIKE(LOWER(LASTTOUCH_TRAFFIC_CAMPAIGN), '^(.*(([^a-df-z]|^)shop|shopping).*)$') OR LOWER(LASTTOUCH_TRAFFIC_SOURCE)='shopping free listings') AND LOWER(LASTTOUCH_TRAFFIC_MEDIUM) NOT LIKE '%paid%' THEN 'Organic Shopping'
    WHEN (LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%social%' AND LOWER(LASTTOUCH_TRAFFIC_MEDIUM) NOT LIKE '%paid%') OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%social-network%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%social-media%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%sm%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%social network%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%social media%' THEN 'Organic Social'
    WHEN (REGEXP_LIKE(LOWER(LASTTOUCH_TRAFFIC_MEDIUM), '^(.*cp.*|ppc|retargeting|paid.*)$')) AND (LOWER(LASTTOUCH_TRAFFIC_CAMPAIGN) LIKE '%#_brand#_%' ESCAPE '#') THEN 'Paid Search - Branded'
    WHEN (REGEXP_LIKE(LOWER(LASTTOUCH_TRAFFIC_MEDIUM), '^(.*cp.*|ppc|retargeting|paid.*)$')) AND (LOWER(LASTTOUCH_TRAFFIC_CAMPAIGN) LIKE '%#_nb#_%' ESCAPE '#') THEN 'Paid Search - NB'
    WHEN (REGEXP_LIKE(LOWER(LASTTOUCH_TRAFFIC_MEDIUM), '^(.*cp.*|ppc|retargeting|paid.*)$')) AND (REGEXP_LIKE(LOWER(LASTTOUCH_TRAFFIC_CAMPAIGN), '^(.*(([^a-df-z]|^)shop|shopping).*)$')) THEN 'Paid Shopping'
    WHEN LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%paidsocial%' THEN 'Paid Social'
    WHEN LOWER(LASTTOUCH_TRAFFIC_SOURCE) LIKE '%sfmc_promo%' THEN 'Promotional Email'
    WHEN LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%referral%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%app%' OR LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%link%' THEN 'Referral'
    WHEN LOWER(LASTTOUCH_TRAFFIC_MEDIUM) LIKE '%sms%' THEN 'SMS Marketing'
    WHEN LOWER(LASTTOUCH_TRAFFIC_SOURCE) LIKE '%sfmc_transactional%' THEN 'Transactional Email'
    WHEN LOWER(LASTTOUCH_TRAFFIC_SOURCE) LIKE '%sfmc_trigger%' THEN 'Triggered Email'
    WHEN LOWER(LASTTOUCH_TRAFFIC_SOURCE) LIKE '%(direct)%' THEN 'Web Direct'
    ELSE NULL
END) as MEDIA_CHANNEL,
(CASE 
    WHEN  LOWER(LASTTOUCH_TRAFFIC_CAMPAIGN) LIKE '%midfunnel%' THEN 'Mid-Funnel'
    WHEN  LOWER(LASTTOUCH_TRAFFIC_CAMPAIGN) LIKE '%ecom%' THEN 'Performance Marketing'
    WHEN  LOWER(LASTTOUCH_TRAFFIC_CAMPAIGN) LIKE '%upperfunnel%' THEN 'Brand'
    WHEN  MEDIA_CHANNEL='Transactional Email' OR MEDIA_CHANNEL='Triggered Email' OR MEDIA_CHANNEL='Promotional Email' THEN 'Email'
    WHEN  MEDIA_CHANNEL='SMS Marketing' THEN 'SMS'
    WHEN  MEDIA_CHANNEL='Affiliates' THEN 'Affiliates'
    ELSE 'UNDEFINED'
END) AS FUNNEL,
Product.DIVISION_NAME,
Product.KEY_CATEGORY_DESC,
Product.BUSINESS_SEGMENT_DESC,
Date.CALDT AS CALDT,
Quarter.ACCTGPRDQTRNUM AS ACCTGPRDQTRNUM,
Quarter.ACCTGPRDQTRLNGNM AS ACCTGPRDQTRLNGNM,
Date.ACCTGPRDYRNM,
SUBSTR(Date.ACCTGPRDYRNM,6,4) AS ACCTGPRDYR,
Quarter.ACCTGPRDQTRNM AS ACCTGPRDQTRNM,
Date.ACCTGPRDMNTHNM,
Date.ACCTGPRDWOYNM,
SUBSTR(Date.ACCTGPRDWOYNM,6,2) AS ACCTGPRDWOYNM_NUMBER,
Date.SEASNNM AS SEASNNM,
Week.ACCTGPRDYRWKNUM AS ACCTGPRDYRWKNUM,
CONCAT(EXTRACT(YEAR FROM Month.ACCTGPRDMNTHENDDT), 
	(CASE 
    WHEN LENGTH(Month.ACCTGPRDMNTHNUM)=1 THEN CONCAT('0', TO_VARCHAR(Month.ACCTGPRDMNTHNUM)) 
    ELSE TO_VARCHAR(Month.ACCTGPRDMNTHNUM) 
    END)
) AS ACCTGPRDMNTHNUM,
CONCAT(SUBSTR(Date.ACCTGPRDYRNM,6,4),' ',Date.ACCTGPRDMNTHNM) AS MONTH_LONG_NM,
CONCAT(SUBSTR(Date.ACCTGPRDYRNM,6,4),' ',Date.ACCTGPRDWOYNM) AS WEEK_LONG_NM,
RANK() OVER (PARTITION BY Date.ACCTGPRDMNTHID ORDER BY CALDT ASC) as DAY_NUM_IN_FISCAL_MONTH,
RANK() OVER (PARTITION BY Date.ACCTGPRDQTRID ORDER BY CALDT ASC) as DAY_NUM_IN_FISCAL_QUARTER,
RANK() OVER (PARTITION BY Date.ACCTGPRDYRID ORDER BY CALDT ASC) as DAY_NUM_IN_FISCAL_YEAR
FROM SECOND_GA4_FLATTEN as GA4
LEFT JOIN LAST_TOUCH_TRAFFIC as Traffic ON Traffic.USER_SESSION_KEY=GA4.USER_SESSION_KEY
LEFT JOIN 
(
Select distinct 
Product.Article,
Product.DIVISION_NAME,
Product.KEY_CATEGORY_DESC,
Product.BUSINESS_SEGMENT_DESC
from "SPARC_BASE"."ECOM_ANALYTICS"."DIM_PRODUCT" as Product
WHERE KEY_CATEGORY_DESC is not null AND BUSINESS_SEGMENT_DESC is not null AND KEY_CATEGORY_DESC!='' AND BUSINESS_SEGMENT_DESC!=''
) as Product ON Product.ARTICLE=GA4.ITEMS_ITEM_ID 
LEFT JOIN "SPARC_BASE"."ECOM_ANALYTICS"."DIM_TIME_CALENDAR_DATE" as Date on Date.CALDT=GA4.EVENT_DATE
LEFT JOIN "SPARC_BASE"."ECOM_ANALYTICS"."DIM_TIME_CALENDAR_QUARTER" as Quarter on Quarter.ACCTGPRDQTRID=Date.ACCTGPRDQTRID
LEFT JOIN "SPARC_BASE"."ECOM_ANALYTICS"."DIM_TIME_CALENDAR_WEEK" as Week on Week.ACCTGPRDWKID=Date.ACCTGPRDWKID
LEFT JOIN "SPARC_BASE"."ECOM_ANALYTICS"."DIM_TIME_CALENDAR_MONTH" as Month on Month.ACCTGPRDMNTHID=Date.ACCTGPRDMNTHID
ORDER BY GA4.USER_SESSION_KEY, GA4.EVENT_DATE DESC
),
GA4_AGGREGATED AS
(
(Select
EVENT_DATE,
USER_SESSION_KEY,
MAX_CHECKOUT_STAGE,
ECOMMERCE_TRANSACTION_ID,
DEVICE_CATEGORY,
sum(UNITS_ORDERED) as UNITS_ORDERED,
ITEMS_ITEM_ID as ARTICLE,
UPPER(FRANCHISE) as FRANCHISE,
GENDER,
sum(ITEMS_ITEM_REVENUE_IN_USD) as ITEMS_ITEM_REVENUE_IN_USD,
LASTTOUCH_TRAFFIC_CAMPAIGN,
LASTTOUCH_TRAFFIC_MEDIUM,
LASTTOUCH_TRAFFIC_SOURCE,
MEDIA_CHANNEL,
FUNNEL,
DIVISION_NAME,
KEY_CATEGORY_DESC,
BUSINESS_SEGMENT_DESC,
CALDT,
ACCTGPRDQTRNUM,
ACCTGPRDQTRLNGNM,
ACCTGPRDYRNM,
ACCTGPRDYR,
ACCTGPRDQTRNM,
ACCTGPRDMNTHNM,
ACCTGPRDWOYNM,
ACCTGPRDWOYNM_NUMBER,
SEASNNM,
ACCTGPRDYRWKNUM,
ACCTGPRDMNTHNUM,
MONTH_LONG_NM,
WEEK_LONG_NM,
DAY_NUM_IN_FISCAL_MONTH,
DAY_NUM_IN_FISCAL_QUARTER,
DAY_NUM_IN_FISCAL_YEAR
from GA4_FINAL
WHERE EVENT_NAME_ORIGINAL='purchase'
GROUP BY
EVENT_DATE,
USER_SESSION_KEY,
MAX_CHECKOUT_STAGE,
ECOMMERCE_TRANSACTION_ID,
DEVICE_CATEGORY,
ARTICLE,
FRANCHISE,
GENDER,
LASTTOUCH_TRAFFIC_CAMPAIGN,
LASTTOUCH_TRAFFIC_MEDIUM,
LASTTOUCH_TRAFFIC_SOURCE,
MEDIA_CHANNEL,
FUNNEL,
DIVISION_NAME,
KEY_CATEGORY_DESC,
BUSINESS_SEGMENT_DESC,
CALDT,
ACCTGPRDQTRNUM,
ACCTGPRDQTRLNGNM,
ACCTGPRDYRNM,
ACCTGPRDYR,
ACCTGPRDQTRNM,
ACCTGPRDMNTHNM,
ACCTGPRDWOYNM,
ACCTGPRDWOYNM_NUMBER,
SEASNNM,
ACCTGPRDYRWKNUM,
ACCTGPRDMNTHNUM,
MONTH_LONG_NM,
WEEK_LONG_NM,
DAY_NUM_IN_FISCAL_MONTH,
DAY_NUM_IN_FISCAL_QUARTER,
DAY_NUM_IN_FISCAL_YEAR
ORDER BY EVENT_DATE, USER_SESSION_KEY DESC
)

UNION

(
Select
EVENT_DATE,
USER_SESSION_KEY,
MAX_CHECKOUT_STAGE,
ECOMMERCE_TRANSACTION_ID,
DEVICE_CATEGORY,
sum(UNITS_ORDERED) as UNITS_ORDERED,
ARTICLE,
UPPER(FRANCHISE) as FRANCHISE,
GENDER,
sum(ITEMS_ITEM_REVENUE_IN_USD) as ITEMS_ITEM_REVENUE_IN_USD,
LASTTOUCH_TRAFFIC_CAMPAIGN,
LASTTOUCH_TRAFFIC_MEDIUM,
LASTTOUCH_TRAFFIC_SOURCE,
MEDIA_CHANNEL,
FUNNEL,
DIVISION_NAME,
KEY_CATEGORY_DESC,
BUSINESS_SEGMENT_DESC,
CALDT,
ACCTGPRDQTRNUM,
ACCTGPRDQTRLNGNM,
ACCTGPRDYRNM,
ACCTGPRDYR,
ACCTGPRDQTRNM,
ACCTGPRDMNTHNM,
ACCTGPRDWOYNM,
ACCTGPRDWOYNM_NUMBER,
SEASNNM,
ACCTGPRDYRWKNUM,
ACCTGPRDMNTHNUM,
MONTH_LONG_NM,
WEEK_LONG_NM,
DAY_NUM_IN_FISCAL_MONTH,
DAY_NUM_IN_FISCAL_QUARTER,
DAY_NUM_IN_FISCAL_YEAR
from(
Select
EVENT_DATE,
USER_SESSION_KEY,
MAX_CHECKOUT_STAGE,
NULL as ECOMMERCE_TRANSACTION_ID,
DEVICE_CATEGORY,
NULL as UNITS_ORDERED,
NULL as ARTICLE,
NULL as FRANCHISE,
NULL as GENDER,
NULL as ITEMS_ITEM_REVENUE_IN_USD,
LASTTOUCH_TRAFFIC_CAMPAIGN,
LASTTOUCH_TRAFFIC_MEDIUM,
LASTTOUCH_TRAFFIC_SOURCE,
MEDIA_CHANNEL,
FUNNEL,
NULL as DIVISION_NAME,
NULL as KEY_CATEGORY_DESC,
NULL as BUSINESS_SEGMENT_DESC,
CALDT,
ACCTGPRDQTRNUM,
ACCTGPRDQTRLNGNM,
ACCTGPRDYRNM,
ACCTGPRDYR,
ACCTGPRDQTRNM,
ACCTGPRDMNTHNM,
ACCTGPRDWOYNM,
ACCTGPRDWOYNM_NUMBER,
SEASNNM,
ACCTGPRDYRWKNUM,
ACCTGPRDMNTHNUM,
MONTH_LONG_NM,
WEEK_LONG_NM,
DAY_NUM_IN_FISCAL_MONTH,
DAY_NUM_IN_FISCAL_QUARTER,
DAY_NUM_IN_FISCAL_YEAR
from GA4_FINAL
WHERE USER_SESSION_KEY NOT IN
(
SELECT distinct USER_SESSION_KEY from GA4_FINAL
WHERE EVENT_NAME_ORIGINAL='purchase'
)
)
GROUP BY
EVENT_DATE,
USER_SESSION_KEY,
MAX_CHECKOUT_STAGE,
ECOMMERCE_TRANSACTION_ID,
DEVICE_CATEGORY,
ARTICLE,
FRANCHISE,
GENDER,
LASTTOUCH_TRAFFIC_CAMPAIGN,
LASTTOUCH_TRAFFIC_MEDIUM,
LASTTOUCH_TRAFFIC_SOURCE,
MEDIA_CHANNEL,
FUNNEL,
DIVISION_NAME,
KEY_CATEGORY_DESC,
BUSINESS_SEGMENT_DESC,
CALDT,
ACCTGPRDQTRNUM,
ACCTGPRDQTRLNGNM,
ACCTGPRDYRNM,
ACCTGPRDYR,
ACCTGPRDQTRNM,
ACCTGPRDMNTHNM,
ACCTGPRDWOYNM,
ACCTGPRDWOYNM_NUMBER,
SEASNNM,
ACCTGPRDYRWKNUM,
ACCTGPRDMNTHNUM,
MONTH_LONG_NM,
WEEK_LONG_NM,
DAY_NUM_IN_FISCAL_MONTH,
DAY_NUM_IN_FISCAL_QUARTER,
DAY_NUM_IN_FISCAL_YEAR
ORDER BY EVENT_DATE, USER_SESSION_KEY DESC
)
)
Select * from GA4_AGGREGATED
