{{ config(materialized="table", database="SPARC_BASE", schema="ECOM_ANALYTICS") }}

Select * from(
(Select USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from (
Select distinct row_number() OVER(PARTITION BY USER_SESSION_KEY ORDER BY EVENT_TIMESTAMP DESC) AS Rank,
USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
WHERE USER_SESSION_KEY IN 
(
    Select distinct USER_SESSION_KEY from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
    WHERE EVENT_NAME_ORIGINAL='purchase'
    AND EP_MEDIUM is not null
    AND EP_CAMPAIGN is not null
    AND EP_SOURCE is not null 
)
AND EVENT_NAME_ORIGINAL='purchase'
AND EP_MEDIUM is not null AND EP_CAMPAIGN is not null AND EP_SOURCE is not null
GROUP BY USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
ORDER BY USER_SESSION_KEY, EVENT_TIMESTAMP DESC
)
WHERE RANK=1)

UNION

(Select USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from (
Select distinct row_number() OVER(PARTITION BY USER_SESSION_KEY ORDER BY EVENT_TIMESTAMP DESC) AS Rank,USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
WHERE USER_SESSION_KEY NOT IN
(
    Select distinct USER_SESSION_KEY from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
    WHERE EVENT_NAME_ORIGINAL='purchase'
    AND EP_MEDIUM is not null
    AND EP_CAMPAIGN is not null
    AND EP_SOURCE is not null
)
AND USER_SESSION_KEY IN
(
    Select distinct USER_SESSION_KEY from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
    WHERE (EP_MEDIUM is not null
    OR EP_CAMPAIGN is not null
    OR EP_SOURCE is not null)
)
AND (EP_MEDIUM is not null
    OR EP_CAMPAIGN is not null
    OR EP_SOURCE is not null)
GROUP BY USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
ORDER BY USER_SESSION_KEY, EVENT_TIMESTAMP DESC
)
WHERE RANK=1)

UNION

(Select USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from (
Select distinct row_number() OVER(PARTITION BY USER_SESSION_KEY ORDER BY EVENT_TIMESTAMP DESC) AS Rank,USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
WHERE USER_SESSION_KEY NOT IN
(
    Select distinct USER_SESSION_KEY from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
    WHERE EVENT_NAME_ORIGINAL='purchase'
    AND EP_MEDIUM is not null
    AND EP_CAMPAIGN is not null
    AND EP_SOURCE is not null 
)
AND USER_SESSION_KEY NOT IN
(
    Select distinct USER_SESSION_KEY from "SPARC_BASE"."ECOM_ANALYTICS"."GA4_SNAPSHOT_V4"
    WHERE (EP_MEDIUM is not null
    OR EP_CAMPAIGN is not null
    OR EP_SOURCE is not null)
)
GROUP BY USER_SESSION_KEY, EVENT_TIMESTAMP,EVENT_NAME_ORIGINAL, EP_MEDIUM, EP_CAMPAIGN, EP_SOURCE
ORDER BY USER_SESSION_KEY, EVENT_TIMESTAMP DESC
)
WHERE RANK=1)
)