version : 2

sources:
  - name : SPARC_RAW
    # adapter: snowflake
    schema: RBOK_GA
    tables:
      - name : ga4_table
        identifier : GA4_EVENTS_RAW
      - name : ga4_table_sample
        identifier : GA4_EVENTS_RAW_SAMPLE
  - name : SPARC_BASE
    schema: ECOM_ANALYTICS
  - name : RBOK_RPT
    schema: ECOM_ANALYTICS    